# What is Numpy ?

Numpy is a python library used for working with arrays.
It also has functions for working in domain of linear algebra , fourier transform and matrices
It was created in 2005 by Travis Oliphant as an Open Source Project which means you can use it freely.
It stands for Numerical-Python

# Why to use Numpy ?

In python we have lists that serve the purpose of arrays but they are slow to process.
Numpy aims to provide an array object that is upto 50X faster than the traditional python lists.
The Array object in numpy is called ndarray.
Arrays are frequently used in Machine learning and Data-Science , where Speed and Resources are important parmaters.

# Which Language is Numpy written in ?

It is a Python library and is partially written in Python, but most of the Parts that require fast computation are written in C/C++.

# Installing Numpy

You can install it using pip command in terminal as pip install numpy.
After Installing Numpy, you can import the library by using import numpy or import numpy as np.
You can check the version of numpy by np.__version__

In [41]:
import numpy as np
np.__version__

'1.17.4'

In [42]:
#Creating Arrays in Numpy
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
#Array Dimensions
#0-D Arrays
arr0 = np.array(42)
arr0

array(42)

In [44]:
#1-D Arrays
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
#2-D Arrays
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
#3-D Arrays
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# Numpy Array Slicing :

Slicing in python means taking elements from one given index to another given index.
We pass slice instead of index like [start:end]
We can also define the step like [start:end:step]
If we don't pass start, start is considered 0
If we don't pass end , it is considered as last element of the dimension
If we don't pass step, it is considered to be 1

In [47]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[1:5]

array([2, 3, 4, 5])

In [48]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[-3:-1]

array([5, 6])

In [49]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[4:]

array([5, 6, 7])

In [50]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[:4]

array([1, 2, 3, 4])

In [51]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[::2]

array([1, 3, 5, 7])

In [52]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[1,2:5]

IndexError: too many indices for array

In [53]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[0:2,1:3]

IndexError: too many indices for array

# Data Types in Numpy
i - Integer

b - Boolean

u - Unsigned Integer

f - Float

c - Complex Float

m - Timedelta

M - Datetime

O - Object

S - String

U - Unicode String

V - Fixed chunk of memory for other type

To Check the datatype of an numpy array, you can use arr.dtype

# The Difference Between Copy and View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [56]:
arr1 = np.array([1,2,3,4,5])
x1 = arr1.copy()
x1

array([1, 2, 3, 4, 5])

In [57]:
arr2 = np.array([6,7,8,9,10])
x2 = arr2.view() #The Difference Between Copy and View
x2

array([ 6,  7,  8,  9, 10])

# Shape of an array

The shape of an array is the number of elements in each dimension.
It can be determined using arr.shape
Integers at every index tells about the number of elements the corresponding dimension has.

In [58]:
arr.shape

(7,)

# Joining Numpy Arrays

Joining means putting contents of two or more arrays in a single array.
In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.
We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [61]:
#Example 1

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

arr

array([1, 2, 3, 4, 5, 6])

In [62]:
#Example 2

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# Joining arrays using Stack Functions

Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.
We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [63]:
#Example 1

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

arr

array([[1, 4],
       [2, 5],
       [3, 6]])

In [64]:
#Example 2 (Stacking along Rows)

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

arr

array([1, 2, 3, 4, 5, 6])

In [65]:
#Example 3 (Stacking along Columns)

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

arr

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
#Example 4 (Stacking along height)

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

arr

array([[[1, 4],
        [2, 5],
        [3, 6]]])

# Splitting Numpy Arrays

Splitting is reverse operation of Joining.
Joining merges multiple arrays into one and Splitting breaks one array into multiple.
We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [67]:
#Example 1

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

newarr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [68]:
#Example 2

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

newarr

[array([1, 2]), array([3, 4]), array([5]), array([6])]

# Numpy Searching Arrays

You can search an array for a certain value, and return the indexes that get a match.
To search an array, use the where() method.

In [69]:
#Example 1

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

x

(array([3, 5, 6], dtype=int64),)

In [70]:
#Example 2

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

x

(array([1, 3, 5, 7], dtype=int64),)

In [71]:
#Example 3

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

x

(array([0, 2, 4, 6], dtype=int64),)

# Example 4 (Search Sorted)

There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [72]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

x

1

# Numpy Sorting Arrays

Sorting means putting elements in an ordered sequence
Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.
The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [73]:
#Example 1

arr = np.array([3, 2, 0, 1])
np.sort(arr)

array([0, 1, 2, 3])

In [74]:
#Example 2

arr = np.array(['banana', 'cherry', 'apple'])
np.sort(arr)

array(['apple', 'banana', 'cherry'], dtype='<U6')

In [75]:
#Example 3

arr = np.array([True, False, True])
np.sort(arr)

array([False,  True,  True])

In [76]:
#Example 4 (Sorting 2-D Array)

arr = np.array([[3, 2, 4], [5, 0, 1]])
np.sort(arr)

array([[2, 3, 4],
       [0, 1, 5]])

# Numpy Filter Array

Getting some elements out of an existing array and creating a new array out of them is called filtering.
In NumPy, you filter an array using a boolean index list.
If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [77]:
#Example 1

arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
newarr

array([41, 43])

In [78]:
#Example 2

arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
newarr

array([43, 44])

In [79]:
#Example 3

arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]
newarr

array([2, 4, 6])

In [80]:
#Random Numbers in Numpy
from numpy import random

#Generate Random Number from 0 to 100
x = random.randint(100)
x

36

In [81]:
#Generate Random Float number between 0 and 1

x = random.rand()
x

0.8738203135127526

In [83]:
#Generate Random Array

x1=random.randint(100, size=(5))
x1

array([79, 17, 80, 94, 46])

In [84]:
x2=random.randint(100, size=(3, 5))
x2

array([[91, 77, 85, 46, 62],
       [20, 67, 92, 59, 88],
       [15, 73, 21, 56,  6]])